node:
    private_key: gefkbuXcLveH2KLp7X2BWO30pLWLTk2y8v6t8hHivlgKTd1x7OWtlOmKUlNSHZd5Bs2INRZhGmTwtWSR5oZykw==
network:
    addresses:
        - /ip4/0.0.0.0/tcp/9000
        - /ip6/::/tcp/9000
peers:
    connection_timeout: 10s
logging:
    level: info
    format: json
    console_output: true
    console_color: true
    file_output: true
    file_name: btc-federation.log
    file_max_size: 10MB
